import "./globals.css";
import TopBar from "@/components/TopBar/TopBar";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const Layout = ({
	children,
}: {
	children: React.ReactNode;
}) => {
	return (
		<html lang="en">
			<body>
				<TopBar />
				{children}
			</body>
		</html>
	);
};

export default Layout;
