import { ClerkProvider } from "@clerk/nextjs";

import "./globals.css";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const Layout = ({
	children,
}: {
	children: React.ReactNode;
}) => {
	return (
		<ClerkProvider>
			<html lang="en">
				<body>{children}</body>
			</html>
		</ClerkProvider>
	);
};

export default Layout;
